// <auto-generated/>
// Copyright (c) Lucas Girouard-Stranks (https://github.com/lithiumtoast). All rights reserved.
// Licensed under the MIT license. See LICENSE file in the Git repository root directory (https://github.com/lithiumtoast/native-tools-cs) for full license information.

using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;

/// <summary>
///     A one dimensional <see cref="byte" /> array terminated by a <c>0x0</c> with a fixed size of 128 bits (16 bytes).
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 16, Pack = 1)]
[SuppressMessage("ReSharper", "CheckNamespace", Justification = "Wants to be a builtin type.")]
[SuppressMessage("Microsoft.Design", "CA1050", Justification = "Wants to be a builtin type.")]
public unsafe struct CString128
{
    [FieldOffset(0)]
    private fixed byte _array[16];
}